[profile.default]
src = "src"
out = "out"
libs = ["lib"]
script = "script"
test = "test"
solc_version = "0.8.24"
via_ir = true

optimizer = true
optimizer_runs = 200

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]
